CREATE DATABASE EMP;
USE EMP;
CREATE TABLE EMPLOYEE(EMPNO CHAR(4),EMP_NAME VARCHAR(20),DEPT VARCHAR(20),SALARY INT,DOJ DATE NOT NULL ,BRANCH VARCHAR(20) );
INSERT INTO EMPLOYEE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E101','AMIT','PRODUCTION',45000,'2000-03-12','BANGLORE');
INSERT INTO EMPLOYEE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E102','AMIT','HR',70000,'2002-03-07','BANGLORE');
INSERT INTO EMPLOYEE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E103','SUNITA','MANAGER',120000,'2001-11-01','MYSORE');
INSERT INTO EMPLOYEE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E105','SUNITA','IT',67000,'2002-01-08','MYSORE');
INSERT INTO EMPLOYEE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E106','MAHESH','CIVIL',145000,'2002-09-20','MUMBAI');
SELECT *FROM EMPLOYEE;

select EMPNO , SALARY from EMPLOYEE;
select avg(SALARY) from EMPLOYEE;
select count(*) from EMPLOYEE;
select count(DISTINCT EMP_NAME) FROM EMPLOYEE;
select SUM(SALARY)FROM EMPLOYEE GROUP BY EMP_NAME;
select * FROM EMPLOYEE WHERE SALARY>120000;
select * FROM EMPLOYEE ORDER BY EMP_NAME DESC;
select * FROM EMPLOYEE WHERE EMP_NAME='AMIT' AND SALARY>50000;
